=== JetBrains/CMake-runner-plugin/regex-parser/resources/parser-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2000-2011 JetBrains s.r.o.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="parser" type="parserType">
  </xs:element>

  <xs:complexType name="parserType">
    <xs:sequence>
      <xs:element name="pattern" type="patternType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="patternType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="regex" type="xs:string" use="required"/>
        <xs:attribute name="output-expr" type="xs:string" default="$0" use="optional"/>
        <xs:attribute name="severity" type="severityType" default="SPECIAL" use="optional"/>
        <xs:attribute name="eat-line" type="xs:boolean" default="true" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="severityType">
    <!-- @see jetbrains.buildServer.makerunner.agent.output.Severity -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="WARN"/>
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="SPECIAL"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== JetBrains/CMake-runner-plugin/cmake-runner-agent/resources/cmake-parser.xml
<?xml version="1.0" encoding="UTF-8" ?>


<parser id="CMake output parser" name="jetbrains.buildServer.cmakerunner.agent.output.CMakeRegexpParser"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="parser-configuration.xsd">

  <!-- Warnings/errors matching -->
  <pattern regex="CMake Warning (\([^\(\)]*\) )?at (.*):(\d+) (\([^\(\)]*\)):" severity="WARN"/>
  <pattern regex="CMake Warning (\([^\(\)]*\) )?in (.*):" severity="WARN"/>
  <pattern regex="CMake Warning:" severity="WARN"/>
  <pattern regex="CMake Error (\([^\(\)]*\) )?at (.*):(\d+) (\([^\(\)]*\)):" severity="ERROR"/>
  <pattern regex="CMake Error (\([^\(\)]*\) )?in (.*):" severity="ERROR"/>
  <pattern regex="CMake Error:" severity="ERROR"/>

  <!-- Out states -->
  <pattern regex="-- Configuring incomplete, errors occurred!" severity="ERROR"/>

  <!-- Call stack parsing -->
  <pattern regex="Call Stack \(most recent call first\):" severity="WARN"/>
  <pattern regex="\.((cmake)|(txt)):\d+ \(.*\)" severity="WARN"/>

  <!-- Errors descriptions -->
  <pattern regex="Could NOT find" severity="ERROR"/>

  <!-- Warnings descriptions -->
  <pattern regex="CMake no longer defines" severity="WARN"/>
  <pattern regex="unused variable \(.*\) '.*'" severity="WARN"/>

  <!-- Compiler warnings -->
  <pattern regex=" warning: " severity="WARN"/>

</parser>

=== JetBrains/CMake-runner-plugin/cmake-runner-agent/resources/make-parser.xml
<?xml version="1.0" encoding="UTF-8" ?>


<parser id="GNU Make output parser" name="jetbrains.buildServer.makerunner.agent.output.MakeRegexpParser"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="parser-configuration.xsd">

  <!-- Folding targets (Additional parsing)-->
  <pattern regex="Making (\S+) in (\S+)"/>
  <pattern regex="make.*: Entering directory `(.*)'"/>
  <pattern regex="make.*: Leaving directory `(.*)'"/>


  <!-- Makefile errors/warnings -->
  <pattern regex=":(\d*): (\*\*\* .*)" severity="ERROR"/>
  <pattern regex="[Mm]akefile:(\d*): warning:" severity="WARN"/>
  <pattern regex=":(\d*): (\S*: No such file or directory)" severity="WARN"/>

  <!-- Targets errors/warnings-->
  <pattern regex="No rule to make target `(.*)'" severity="ERROR"/>
  <pattern regex="make.*: (Target (.*) not remade because of errors.)" severity="ERROR"/>

  <pattern regex="make.*: \*\*\* \[\S+\]" severity="ERROR"/>
  <pattern regex="make.*:(.*Error.*\(ignored\))" severity="INFO"/>
  <pattern regex="make.*: \*\*\* " severity="ERROR"/>
  <pattern regex="Error:\s*" severity="ERROR"/>

  <pattern regex="command not found" severity="ERROR"/>

  <pattern regex="\s*\*\*\*" severity="ERROR"/>


  <pattern regex="make.*\[.*\] Error [\-]?\d*" severity="WARN"/>
  <pattern regex="make.*: (Circular .* dependency dropped.)" severity="WARN"/>

  <!-- Compiler warnings -->
  <pattern regex=" warning: " severity="WARN"/>

</parser>

=== JetBrains/CMake-runner-plugin/make-runner-agent/resources/make-parser.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright 2000-2011 JetBrains s.r.o.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<parser id="GNU Make output parser" name="jetbrains.buildServer.makerunner.agent.output.MakeRegexpParser"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="parser-configuration.xsd">

  <!-- Folding targets (Additional parsing)-->
  <pattern regex="Making (\S+) in (\S+)"/>
  <pattern regex=".*make.*: Leaving directory `(.*)'"/>

  <!-- do nothing-->
  <pattern regex=".*make.*: Entering directory `(.*)'" severity="INFO"/>


  <!-- Makefile errors/warnings -->
  <pattern regex="(.*):(\d*): (\*\*\* .*)" output-expr="In file '$1' at line '$2' : '$3'" severity="ERROR"/>
  <pattern regex="(.*[Mm]akefile):(\d*): warning: (.*)" output-expr="In file '$1' at line '$2' : '$3'" severity="WARN"/>
  <pattern regex="(.*):(\d*): (\S*: No such file or directory)" output-expr="In file '$1' at line '$2' : '$3'"
           severity="WARN"/>

  <!-- Targets errors/warnings-->
  <pattern regex="No rule to make target `(.*)'\." severity="ERROR"/>
  <pattern regex=".*make.*: (Target (.*) not remade because of errors.)" output-expr="$1" severity="ERROR"/>

  <pattern regex=".*make.*: \*\*\* (\[\S+\] .*)" output-expr="$1" severity="ERROR"/>
  <pattern regex=".*make.*:(.*Error.*\(ignored\))" output-expr="$1" severity="INFO"/>
  <pattern regex=".*make.*: \*\*\* (.*)" output-expr="$1" severity="ERROR"/>
  <pattern regex="Error:\s*(.*)" severity="ERROR"/>

  <pattern regex=".*command not found.*" severity="ERROR"/>
  <pattern regex=".*command not found.*" severity="ERROR"/>


  <pattern regex=".*make.*\[.*\] (Error [\-]?\d*.*)" output-expr="$1" severity="WARN"/>
  <pattern regex=".*make.*: (Circular .* dependency dropped.)" output-expr="$1" severity="WARN"/>

</parser>
